modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Ellemes/container-library/issues/"
license = "0BSD"

[[mods]]
modId = "ellemes_container_lib"
version = "${version}"
displayName = "Ellemes' Container Library"
authors = "Ellemes"
logoFile = "icon.png"

[[dependencies.ellemes_container_lib]]
modId = "forge"
mandatory = true
versionRange = "[41.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ellemes_container_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
