modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/NinjaPhenix/container-library/issues/"
license = "0BSD"

[[mods]]
modId = "ninjaphenix_container_lib"
version = "${version}"
displayName = "NinjaPhenix's Container Library"
authors = "NinjaPhenix"
logoFile = "icon.png"

[[dependencies.ninjaphenix_container_lib]]
modId = "forge"
mandatory = true
versionRange = "[38.0.14,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ninjaphenix_container_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
