modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/NinjaPhenix/container-library/issues/"
license = "0BSD"

[[mods]]
modId = "ninjaphenix_container_lib"
version = "${version}"
displayName = "NinjaPhenix's Container Library"
authors = "NinjaPhenix"
logoFile = "icon.png"

[[dependencies.ninjaphenix_container_lib]]
modId = "forge"
mandatory = true
versionRange = "[36.2.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ninjaphenix_container_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
