modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/Ellemes/container-library/issues/"
license = "0BSD"

[[mods]]
modId = "ellemes_container_lib_test"
version = "0.0.0"
displayName = "Ellemes' Container Library Tests"
authors = "Ellemes"
